-- UserRole data
INSERT INTO user_role (id, name, role) VALUES (1, 'ADMIN', 'ADMIN');
-- User
INSERT INTO users (id, first_name, last_name, email, username, enabled, password, language, user_role_id) VALUES (1,'Admin', 'Fodd','admin@email.com','admin@email.com', TRUE, '$2a$10$xxI6/lZ2J3T7/FsK8IQuEetMpjJOTeVaRkpwQ0ITQyTVFLKIfEApW','pt_BR', 1);
INSERT INTO users (id, first_name, last_name, email, username, enabled, password, language, user_role_id) VALUES (2,'Joze', 'Carlos','jozecarlos@email.com','jozecarlos@email.com', TRUE, '$2a$10$xxI6/lZ2J3T7/FsK8IQuEetMpjJOTeVaRkpwQ0ITQyTVFLKIfEApW','pt_BR', 1);
INSERT INTO users (id, first_name, last_name, email, username, enabled, password, language, user_role_id) VALUES (3,'Rodrigo', 'Silva','rodrigo@email.com', 'rodrigo@email.com',TRUE, '$2a$10$xxI6/lZ2J3T7/FsK8IQuEetMpjJOTeVaRkpwQ0ITQyTVFLKIfEApW','pt_BR', 1);
INSERT INTO users (id, first_name, last_name, email, username, enabled, password, language, user_role_id) VALUES (4,'Edmilson', 'Silva','edmilson@email.com','edmilson@email.com', TRUE, '$2a$10$xxI6/lZ2J3T7/FsK8IQuEetMpjJOTeVaRkpwQ0ITQyTVFLKIfEApW','pt_BR', 1);


-- Preservation methods
INSERT INTO preservation_method (id, "name") VALUES (16, 'CANNED');
INSERT INTO preservation_method (id, "name") VALUES (3, 'ADDITIVES');
INSERT INTO preservation_method (id, "name") VALUES (14, 'CANNED_IN_OIL');
INSERT INTO preservation_method (id, "name") VALUES (5, 'SALTED');
INSERT INTO preservation_method (id, "name") VALUES (10, 'PASTEURIZED');
INSERT INTO preservation_method (id, "name") VALUES (9, 'BLANCHED');
INSERT INTO preservation_method (id, "name") VALUES (12, 'IRRADIATED');
INSERT INTO preservation_method (id, "name") VALUES (7, 'SMOKED');
INSERT INTO preservation_method (id, "name") VALUES (2, 'CHILLED');
INSERT INTO preservation_method (id, "name") VALUES (15, 'CANNED_IN_SYRUP');
INSERT INTO preservation_method (id, "name") VALUES (4, 'FREEZE_DRIED');
INSERT INTO preservation_method (id, "name") VALUES (11, 'STERLIZED');
INSERT INTO preservation_method (id, "name") VALUES (8, 'FILTRATED');
INSERT INTO preservation_method (id, "name") VALUES (13, 'VACUUM');
INSERT INTO preservation_method (id, "name") VALUES (6, 'CURED');
INSERT INTO preservation_method (id, "name") VALUES (1, 'FROZEN');

-- Cooking degree
INSERT INTO cooking_degree (id, "name") VALUES (3, 'FULLY_COOKED');
INSERT INTO cooking_degree (id, "name") VALUES (5, 'MEDIUM');
INSERT INTO cooking_degree (id, "name") VALUES (7, 'MEDIUM_WELL');
INSERT INTO cooking_degree (id, "name") VALUES (2, 'PARTIALLY_COOKED');
INSERT INTO cooking_degree (id, "name") VALUES (4, 'RARE');
INSERT INTO cooking_degree (id, "name") VALUES (8, 'WELL_DONE');
INSERT INTO cooking_degree (id, "name") VALUES (6, 'MEDIUM_RARE');
INSERT INTO cooking_degree (id, "name") VALUES (1, 'RAW');

-- Food group
INSERT INTO food_group (id, "name") VALUES (3, 'LEGUMES_AND_DERIVATIVES');
INSERT INTO food_group (id, "name") VALUES (5, 'VEGETABLES');
INSERT INTO food_group (id, "name") VALUES (10, 'MILK');
INSERT INTO food_group (id, "name") VALUES (9, 'FISH_AND_SEAFOOD');
INSERT INTO food_group (id, "name") VALUES (12, 'MISCELLANEOUS');
INSERT INTO food_group (id, "name") VALUES (7, 'MEAT_AND_DERIVATIVES');
INSERT INTO food_group (id, "name") VALUES (2, 'STARCHY_ROOTS_AND_TUBERS');
INSERT INTO food_group (id, "name") VALUES (4, 'NUTS_AND_SEEDS');
INSERT INTO food_group (id, "name") VALUES (11, 'HERBS_AND_SPICES');
INSERT INTO food_group (id, "name") VALUES (8, 'EGGS');
INSERT INTO food_group (id, "name") VALUES (6, 'FRUITS_AND_DERIVATIVES');
INSERT INTO food_group (id, "name") VALUES (1, 'CEREALS_AND_DERIVATIVES');

-- Food type
INSERT INTO food_type (id, "name") VALUES (2, 'MIXED');
INSERT INTO food_type (id, "name") VALUES (1, 'SINGLE');

-- Food processing
INSERT INTO food_processing (id, "name") VALUES (16, 'PARBOILED');
INSERT INTO food_processing (id, "name") VALUES (3, 'BOILED');
INSERT INTO food_processing (id, "name") VALUES (14, 'POACHED');
INSERT INTO food_processing (id, "name") VALUES (5, 'MICROWAVED');
INSERT INTO food_processing (id, "name") VALUES (10, 'SHALLOW_FRIED');
INSERT INTO food_processing (id, "name") VALUES (9, 'DEEP_FRIED');
INSERT INTO food_processing (id, "name") VALUES (12, 'STIR_FRIED');
INSERT INTO food_processing (id, "name") VALUES (7, 'STEAMED_UNDER_PRESSURE');
INSERT INTO food_processing (id, "name") VALUES (2, 'BAKED');
INSERT INTO food_processing (id, "name") VALUES (15, 'FERMENTED');
INSERT INTO food_processing (id, "name") VALUES (4, 'BRAISED');
INSERT INTO food_processing (id, "name") VALUES (11, 'SAUTEED');
INSERT INTO food_processing (id, "name") VALUES (8, 'TOASTED');
INSERT INTO food_processing (id, "name") VALUES (13, 'COOKED_IN_WATER_BATH');
INSERT INTO food_processing (id, "name") VALUES (6, 'STEAMED');
INSERT INTO food_processing (id, "name") VALUES (1, 'DRIED');

-- Part plant / animal
INSERT INTO part_plant_animal (id, "name") VALUES (16, 'CORN');
INSERT INTO part_plant_animal (id, "name") VALUES (9, 'NUT');
INSERT INTO part_plant_animal (id, "name") VALUES (24, 'HEART');
INSERT INTO part_plant_animal (id, "name") VALUES (17, 'RHIZOME');
INSERT INTO part_plant_animal (id, "name") VALUES (8, 'SEED');
INSERT INTO part_plant_animal (id, "name") VALUES (23, 'FLOWER');
INSERT INTO part_plant_animal (id, "name") VALUES (10, 'ROOT');
INSERT INTO part_plant_animal (id, "name") VALUES (22, 'ROOT_TUBER_BULB_WOUT_PEEL');
INSERT INTO part_plant_animal (id, "name") VALUES (7, 'CORE');
INSERT INTO part_plant_animal (id, "name") VALUES (2, 'FRUIT_W_PEEL_R_CORE_SEED');
INSERT INTO part_plant_animal (id, "name") VALUES (15, 'BULB');
INSERT INTO part_plant_animal (id, "name") VALUES (25, 'MEAT');
INSERT INTO part_plant_animal (id, "name") VALUES (5, 'FRUIT_INDUSTRIALIZED_PULP');
INSERT INTO part_plant_animal (id, "name") VALUES (20, 'ROOT_TUBER_BULB_PEEL_ONLY');
INSERT INTO part_plant_animal (id, "name") VALUES (27, 'BREAST');
INSERT INTO part_plant_animal (id, "name") VALUES (12, 'LEAF');
INSERT INTO part_plant_animal (id, "name") VALUES (19, 'BULB');
INSERT INTO part_plant_animal (id, "name") VALUES (4, 'FRUIT_R_PEEL_R_CORE_SEED');
INSERT INTO part_plant_animal (id, "name") VALUES (13, 'LEAVES_AND_STEM');
INSERT INTO part_plant_animal (id, "name") VALUES (28, 'FILLET');
INSERT INTO part_plant_animal (id, "name") VALUES (18, 'TUBER');
INSERT INTO part_plant_animal (id, "name") VALUES (3, 'FRUIT_R_PEEL_W_CORE_SEED');
INSERT INTO part_plant_animal (id, "name") VALUES (14, 'STEM');
INSERT INTO part_plant_animal (id, "name") VALUES (21, 'ROOT_TUBER_BULB_W_PEEL');
INSERT INTO part_plant_animal (id, "name") VALUES (26, 'LEG');
INSERT INTO part_plant_animal (id, "name") VALUES (11, 'POD');
INSERT INTO part_plant_animal (id, "name") VALUES (6, 'PEEL');
INSERT INTO part_plant_animal (id, "name") VALUES (1, 'FRUIT_WHOLE');

-- Agricultural production conditions
INSERT INTO agricultural_production_condition (id, "name") VALUES (3, 'HYDROPONIC');
INSERT INTO agricultural_production_condition (id, "name") VALUES (5, 'MECHANICALLY_HARVESTED');
INSERT INTO agricultural_production_condition (id, "name") VALUES (7, 'FARMED');
INSERT INTO agricultural_production_condition (id, "name") VALUES (2, 'AGROECOLOGICAL');
INSERT INTO agricultural_production_condition (id, "name") VALUES (4, 'HAND_PICKED');
INSERT INTO agricultural_production_condition (id, "name") VALUES (6, 'WILD');
INSERT INTO agricultural_production_condition (id, "name") VALUES (1, 'ORGANIC');

-- Ripeness maturity
INSERT INTO ripeness_maturity (id, "name") VALUES (3, 'PARTIALLY_RIPE');
INSERT INTO ripeness_maturity (id, "name") VALUES (2, 'IMMATURE');
INSERT INTO ripeness_maturity (id, "name") VALUES (1, 'RIPE');

-- Storage conditions
INSERT INTO storage_condition (id, "name") VALUES (3, 'REFRIGERATOR');
INSERT INTO storage_condition (id, "name") VALUES (2, 'FREEZER');
INSERT INTO storage_condition (id, "name") VALUES (1, 'ROOM_TEMPERATURE');

-- Contact surface container
INSERT INTO contact_surface_container (id, "name") VALUES (3, 'METAL');
INSERT INTO contact_surface_container (id, "name") VALUES (5, 'STEEL');
INSERT INTO contact_surface_container (id, "name") VALUES (10, 'WAX');
INSERT INTO contact_surface_container (id, "name") VALUES (9, 'FABRIC');
INSERT INTO contact_surface_container (id, "name") VALUES (12, 'WOOD');
INSERT INTO contact_surface_container (id, "name") VALUES (7, 'PAPER');
INSERT INTO contact_surface_container (id, "name") VALUES (2, 'GLASS');
INSERT INTO contact_surface_container (id, "name") VALUES (4, 'ALUMINUM');
INSERT INTO contact_surface_container (id, "name") VALUES (11, 'IRON');
INSERT INTO contact_surface_container (id, "name") VALUES (8, 'PLASTIC');
INSERT INTO contact_surface_container (id, "name") VALUES (6, 'TIN');
INSERT INTO contact_surface_container (id, "name") VALUES (1, 'CERAMIC');

-- Physical state
INSERT INTO physical_state (id, "name") VALUES (3, 'SEMI_SOLID');
INSERT INTO physical_state (id, "name") VALUES (2, 'LIQUID');
INSERT INTO physical_state (id, "name") VALUES (1, 'SOLID');

-- Colour
INSERT INTO colour (id, "name") VALUES (16, 'LIGHT_YELLOW');
INSERT INTO colour (id, "name") VALUES (5, 'BLACK');
INSERT INTO colour (id, "name") VALUES (9, 'VIOLET');
INSERT INTO colour (id, "name") VALUES (12, 'PURPLE_SKIN_WHITE_FLESH');
INSERT INTO colour (id, "name") VALUES (17, 'LIGHT_ORANGE');
INSERT INTO colour (id, "name") VALUES (4, 'ORANGE');
INSERT INTO colour (id, "name") VALUES (8, 'PURPLE');
INSERT INTO colour (id, "name") VALUES (13, 'ORANGE_SKIN_YELLOW_FLESH');
INSERT INTO colour (id, "name") VALUES (3, 'GREEN');
INSERT INTO colour (id, "name") VALUES (14, 'DARK_GREEN');
INSERT INTO colour (id, "name") VALUES (10, 'WHITE');
INSERT INTO colour (id, "name") VALUES (7, 'LIGHT_BROWN');
INSERT INTO colour (id, "name") VALUES (2, 'YELLOW');
INSERT INTO colour (id, "name") VALUES (15, 'LIGHT_GREEN');
INSERT INTO colour (id, "name") VALUES (11, 'YELLOW_SKIN_WHITE_FLESH');
INSERT INTO colour (id, "name") VALUES (6, 'BROWN');
INSERT INTO colour (id, "name") VALUES (1, 'RED');

-- Reference type
INSERT INTO reference_type (id, "name") VALUES (3, 'ARTICLE_IN_REPORT');
INSERT INTO reference_type (id, "name") VALUES (14, 'REFERENCE_TYPE_NOT_KNOW');
INSERT INTO reference_type (id, "name") VALUES (5, 'FILE_OR_DATABASE');
INSERT INTO reference_type (id, "name") VALUES (10, 'REPORT');
INSERT INTO reference_type (id, "name") VALUES (9, 'PHAMPLET_FOLDER');
INSERT INTO reference_type (id, "name") VALUES (12, 'WEBPAGE');
INSERT INTO reference_type (id, "name") VALUES (7, 'PRODUCT_LABEL');
INSERT INTO reference_type (id, "name") VALUES (2, 'ARTICLE_IN_JOURNAL');
INSERT INTO reference_type (id, "name") VALUES (4, 'BOOK');
INSERT INTO reference_type (id, "name") VALUES (11, 'SOFTWARE');
INSERT INTO reference_type (id, "name") VALUES (8, 'PERSONAL_COMMUNICATION');
INSERT INTO reference_type (id, "name") VALUES (13, 'OTHER_REFERENCE_TYPE');
INSERT INTO reference_type (id, "name") VALUES (6, 'JOURNAL_ISSUE');
INSERT INTO reference_type (id, "name") VALUES (1, 'ARTICLE_IN_BOOK');

-- Country
INSERT INTO country (id, "name") VALUES (1, 'BRAZIL');

-- State
INSERT INTO "state" (id, "name", country_id) VALUES (1, 'SAO_PAULO', 1);

-- Nutrient types
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (340, 'NITRI', 'MG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (386, 'NIAEQ', 'MG', 33);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (258, 'F22D4N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (185, 'F22D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (32, 'RIBOFLAVIN_B2', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (130, 'F18D1TN3', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (57, 'AAT24', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (384, 'THIA-', 'MG', 31);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (67, 'HYP', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (256, 'F20D4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (195, 'F16D1CN7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (30, 'VITAMIN_K', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (128, 'F30D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (228, 'F22D2', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (323, 'K', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (71, 'MET', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (254, 'F20D4N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (344, 'VITA', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (453, 'STGSTR', 'MG', 49);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (165, 'F16D1T', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (116, 'F17D0I', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (230, 'F16D3N4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (28, 'VITAMIN_E', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (346, 'VITAACT', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (183, 'F18D1N11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (203, 'F16D2N9', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (65, 'GLY', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (24, 'MINERALS', NULL, 23);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (281, 'FIBTG', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (234, 'F18D3N4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (36, 'VITAMIN_B6', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (321, 'CU', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (120, 'F18D0AI', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (342, 'SR', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (295, 'CHITIN', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (34, 'FOLATE', '', 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (177, 'F17D1CN7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (167, 'F16D1TN7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (59, 'ARG', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (335, 'AS', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (380, 'CHOCALOH', 'MCG', 29);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (138, 'F20D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (301, 'SUGNRD', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (79, 'TYR', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (252, 'F18D4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (175, 'F18D1N5', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (391, 'FOL-', 'MCG', 34);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (283, 'FIBAD', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (446, 'CHOL-', 'MG', 48);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (232, 'F18D3CN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (26, 'VITAMINS', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (124, 'F22D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (173, 'F22D1T', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (339, 'NITRA', 'MG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (114, 'F16D0AI', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (420, 'CAFFAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (212, 'F18D2TTN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (451, 'SITSTR', 'MG', 49);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (169, 'F20D1T', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (242, 'F20D3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (179, 'F15D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (415, 'KAEMF', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (419, 'TAN', 'MG', 42);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (324, 'MG', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (413, 'FLAVO', 'MG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (244, 'F22D3N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (389, 'FOLSUM', 'MCG', 34);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (330, 'SE', 'MCG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (402, 'VITC-', 'MG', 39);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (126, 'F24D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (274, 'DGLY', 'G', 16);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (69, 'LEU', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (18, 'CARBOHYDRATES', NULL, 17);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (112, 'F16D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (136, 'F19D1N10', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (73, 'PHE', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (55, 'PROTCNA', 'G', 7);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (328, 'P', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (38, 'BIOTIN', '', 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (311, 'GLYC', 'G', 21);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (240, 'F20D3N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (193, 'F18D1TN2', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (248, 'F18D4N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (393, 'VITB6A', 'MG', 36);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (75, 'SER', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (326, 'NA', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (409, 'PROCYA', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (267, 'F22D5', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (151, 'F20D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (246, 'F16D4N1', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (108, 'F14D0I', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (22, 'SUGARS', NULL, 17);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (236, 'F18D3TN3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (449, 'CAMT', 'MG', 49);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (407, 'CATECT', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (149, 'F14D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (154, 'F24D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (20, 'POLYOLS', '', 17);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (317, 'CA', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (110, 'F15D0I', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (189, 'F17D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (238, 'F18D3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (405, 'PAPOLY', 'MG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (40, 'BIOACTIVE_COMPOUNDS', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (400, 'ASCL', 'MG', 39);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (337, 'CD', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (191, 'F22D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (319, 'CO', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (411, 'NARING', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (1, 'ENERGY', 'KCAL', NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (437, 'OXALAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (161, 'F24D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (142, 'F22D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (417, 'QUERCE', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (313, 'STARES3', 'G', 21);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (94, 'FAPUN6', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (289, 'FIBSOL', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (89, 'FASAT', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (434, 'BENAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (140, 'F16D1CN9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (2, 'SUM_PROXIMATES', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (287, 'NSP', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (350, 'ATX', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (205, 'F16D2N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (443, 'TARAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (372, 'TOCTRA', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (285, 'FIBC', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (309, 'LACS', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (197, 'F18D1C', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (4, 'ASH', 'G', NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (216, 'F18D2N5', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (152, 'F18D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (250, 'F18D4N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (439, 'QUINAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (327, 'NI', 'MCG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (378, 'VITDEQ', 'MCG', 29);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (163, 'F15D1N10', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (399, 'VITC', 'MG', 39);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (92, 'FATRN', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (45, 'ORGANIC_ACIDS', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (291, 'CELLU', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (218, 'F18D2', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (91, 'FAPU', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (171, 'F20D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (134, 'F19D1N11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (376, 'VITE-', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (8, 'AMINO_ACIDS', NULL, 6);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (262, 'F20D5N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (132, 'F18D1TN9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (359, 'CRYPXB', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (430, 'SYRAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (395, 'PYRXN', 'MG', 36);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (352, 'CARTA', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (214, 'F18D2TN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (87, 'FAT-', 'G', 11);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (260, 'F22D4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (315, 'SORTL', 'MG', 20);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (96, 'FAN6', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (354, 'CARTBCIS', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (85, 'FAT', 'G', 11);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (44, 'OTHER', '', 40);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (98, 'FAFRE', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (333, 'MO', 'MCG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (49, 'PLANT_STEROLS', '', 47);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (207, 'F16D2', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (422, 'CINAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (209, 'F18D2C9T11', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (272, 'F24D6N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (6, 'PROTEIN', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (16, 'FAT_COMPONENTS', NULL, 10);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (371, 'TOCPHG', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (243, 'F22D3N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (83, 'NNP', 'MG', 9);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (270, 'F22D6N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (222, 'F20D2C', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (211, 'F18D2TCON', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (201, 'F18D1T', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (306, 'SUCS', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (369, 'TOCPHB', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (100, 'F6D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (159, 'F10D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (268, 'F22D6N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (46, 'FLAVONOIDS', NULL, 40);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (382, 'VITK', 'MCG', 30);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (77, 'THR', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (102, 'F10D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (424, 'ELLAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (157, 'F16D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (357, 'CRYPX', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (146, 'F20D1CN9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (180, 'F18D1CN4', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (441, 'SHIKAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (235, 'F18D3CN3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (14, 'FATTY_ACIDS_MONOUNSATURATED', NULL, 10);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (363, 'NEOX', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (199, 'F17D1N5', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (304, 'GLUS', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (220, 'F20D2CN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (186, 'F20D1CN11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (428, 'PCHOUAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (361, 'LUTNZEA', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (48, 'CHOLESTEROL', '', 47);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (298, 'SUGAR', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (106, 'F13D0i', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (348, 'CARTOID', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (426, 'GALAAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (374, 'TOCTRD', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (10, 'LIPIDS', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (224, 'F22D2N9', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (182, 'F20D1N11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (123, 'F21D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (279, 'CHOCDF', 'G', 18);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (12, 'FATTY_ACIDS_TOTAL', '', 10);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (226, 'F22D2N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (365, 'VIOLX', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (277, 'PHOLIP', 'G', 16);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (62, 'CYS', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (119, 'F18D0I', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (144, 'F18D1TN8', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (104, 'F12D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (60, 'ASN', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (296, 'PSACNC', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (81, 'XN', '', 9);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (31, 'THIAMIN_B1', '', 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (322, 'FE', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (129, 'F14D1CN5', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (385, 'RIBF', 'MG', 32);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (66, 'HIS', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (345, 'RETOL', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (194, 'F18D1CN11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (184, 'F16D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (257, 'F22D4N9', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (35, 'PANTHOTENIC_ACID', '', 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (33, 'NIACIIN', '', 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (131, 'F16D1N5', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (172, 'F18D1CN6', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (56, 'PROT-', 'G', 7);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (367, 'VITE', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (387, 'NIA', 'MG', 33);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (259, 'F22D4N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (318, 'CLD', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (280, 'CHOAVLM', 'G', 18);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (408, 'EPICATEC', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (117, 'F17D0AI', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (229, 'F16D3N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (174, 'F18D1CN9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (111, 'F15D0AI', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (452, 'SQUAL', 'MG', 49);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (137, 'F17D1N8', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (39, 'VITAMIN_C', '', 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (29, 'VITAMIN_D', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (347, 'VITA-', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (255, 'F20D4N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (233, 'F18D3N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (139, 'F12D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (58, 'ALA', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (121, 'F19D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (390, 'FOL', 'MCG', 34);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (164, 'F18D1CN7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (320, 'CR', 'MCG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (231, 'F16D3N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (103, 'F11D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (292, 'LIGN', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (64, 'GLU', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (343, 'VITA_RAE', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (388, 'NIA-', 'MG', 33);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (25, 'TOXIC_TRACE_ELEMENTS_CONTAMINANTS', NULL, 23);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (166, 'F14D1T', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (381, 'ERGCAL', 'MCG', 29);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (37, 'VITAMIN_B12', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (27, 'VITAMIN_A_CAROTENOIDS', NULL, 26);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (125, 'F23D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (341, 'PB', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (253, 'F20D4CN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (294, 'MUCIL', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (282, 'FIBTS', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (273, 'TGLY', 'G', 16);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (423, 'CITAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (329, 'S', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (450, 'SAPON', 'MG', 49);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (403, 'ANTCYAN', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (178, 'F16D1N11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (275, 'MGLY', 'G', 16);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (334, 'AL', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (412, 'LUTEOL', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (17, 'CARBOHYDRATES', NULL, NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (115, 'F17D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (300, 'SUGRD', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (68, 'ILE', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (241, 'F20D3N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (414, 'ISOHA', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (113, 'F16D0I', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (325, 'MN', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (54, 'PROTCNT', 'G', 7);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (239, 'F20D3N9', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (302, 'SUGAR-', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (19, 'FIBRE', '', 17);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (133, 'F22D1N11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (74, 'PRO', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (245, 'F16D4N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (421, 'CHLRAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (176, 'F18D1TN7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (448, 'BRASTR', 'MG', 49);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (127, 'F26D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (264, 'F21D5N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (392, 'PANTAC', 'MG', 35);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (72, 'ORN', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (404, 'FLAVD', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (42, 'TANNINS', '', 40);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (70, 'LYS', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (153, 'F17D1N10', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (148, 'F14D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (249, 'F18D4CN3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (23, 'MINERALS_TRACE_ELEMENTS', '', NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (331, 'V', 'MCG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (310, 'AMYS', 'G', 21);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (406, 'CATEC', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (192, 'F15D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (150, 'F18D1CN3', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (43, 'PHENOLIC_ACIDS', NULL, 40);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (266, 'F22D5N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (397, 'VITB12', 'MCG', 37);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (338, 'HG', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (316, 'B', 'MCG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (190, 'F20D1N12', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (401, 'ASCDL', 'MG', 39);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (237, 'F18D3N3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (410, 'HESPD', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (21, 'POLYSACCHARIDES', '', 17);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (155, 'F15D1N8', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (247, 'F16D4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (188, 'F18D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (336, 'BA', 'MCG', 25);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (109, 'F15D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (398, 'BIOT', 'MCG', 38);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (312, 'STARCH', 'G', 21);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (286, 'FIB-', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (217, 'F18D2N4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (206, 'F16D2N4', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (84, 'NPRO', 'G', 9);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (284, 'FIBND', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (396, 'PYRXNHCL', 'MG', 36);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (196, 'F24D1N11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (95, 'FAPUN3', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (288, 'FIBINS', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (351, 'CAROT', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (88, 'FACID', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (435, 'FUMAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (436, 'MALAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (160, 'F14D1N5', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (308, 'MALS', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (93, 'FAPUN9', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (418, 'RUTIN', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (349, 'ANTHX', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (261, 'F20D5CN3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (90, 'FAMS', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (433, 'ACEAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (290, 'PECT', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (438, 'PHYTAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (143, 'F18D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (373, 'TOCTRB', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (162, 'F18D1CN5', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (3, 'WATER', 'G', NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (219, 'F20D2N9', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (265, 'F22D5N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (107, 'F14D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (97, 'FAN3', 'G', 12);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (170, 'F17D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (377, 'VITD', 'MCG', 29);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (353, 'CARTB', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (431, 'VANAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (215, 'F18D2N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (76, 'TAU', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (332, 'ZN', 'MG', 24);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (440, 'SALAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (204, 'F16D2N7', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (7, 'PROTEIN_TOTAL', NULL, 6);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (251, 'F18D4N1', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (86, 'FATCE', 'G', 11);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (303, 'FRUS', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (213, 'F18D2CN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (210, 'F18D2T10C12', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (5, 'ALCOHOL', 'G', NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (442, 'SUCAC', 'MG', 45);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (416, 'MYRIC', 'MCG', 46);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (394, 'VITB6-', 'MG', 36);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (314, 'MANTL', 'MG', 20);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (208, 'F17D2', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (99, 'F4D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (168, 'F18D1TN6', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (263, 'F20D5', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (135, 'F16D1C', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (355, 'CARTBEQ', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (432, 'RESVTROL', 'MCG', 44);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (297, 'WAX', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (78, 'TRP', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (307, 'TRES', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (425, 'FERAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (370, 'TOCPHD', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (158, 'F16D1N8', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (147, 'F17D1CN8', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (445, 'CHOLE', 'MG', 48);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (223, 'F20D2', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (15, 'FATTY_ACIDS_POLYUNSATURATED', NULL, 10);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (356, 'CARTG', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (293, 'HEMCEL', 'G', 19);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (181, 'F14D1', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (271, 'F22D6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (447, 'CHOLEST', 'MG', 48);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (221, 'F20D2N6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (202, 'F15D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (101, 'F8D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (358, 'CRYPXA', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (13, 'FATTY_ACIDS_SATURATED', NULL, 10);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (383, 'THIA', 'MG', 31);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (200, 'F16D1N9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (368, 'TOCPHA', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (156, 'F20D1N8', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (225, 'F22D2CN6', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (198, 'F18D1TN11', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (276, 'GLYLIP', 'G', 16);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (122, 'F20D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (9, 'NITROGEN', NULL, 6);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (362, 'LYCPN', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (47, 'STEROLS', '', NULL);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (269, 'F22D6CN3', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (105, 'F13D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (364, 'NEUROSP', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (305, 'XYLS', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (278, 'CHOAVLDF', 'G', 18);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (118, 'F18D0', 'G', 13);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (187, 'F17D1N7', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (429, 'SINPAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (379, 'CHOCAL', 'MCG', 29);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (141, 'F24D1CN9', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (82, 'NT', NULL, 9);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (61, 'ASP', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (366, 'ZEA', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (427, 'GALLAC', 'MG', 43);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (299, 'SUGARM', 'G', 22);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (227, 'F22D2C', 'G', 15);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (80, 'VAL', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (63, 'GLN', 'MG', 8);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (360, 'LUTN', 'MCG', 27);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (375, 'TOCTRG', 'MG', 28);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (145, 'F15D1N6', 'G', 14);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (11, 'FAT_TOTAL', NULL, 10);
INSERT INTO nutrient_type (id, "name", unit, parent_id) VALUES (444, 'OA', 'G', 45);



-- ####### MOCK DATA - FOOD COMPOSITION #######
INSERT INTO sampling_origin (id, city, latitude, longitude, country_id, state_id) VALUES (1, 'São Paulo', 46.6333, 23.55, 1, 1);
INSERT INTO sampling (id, analysis_reason, analytical_replicates_number, analytical_samples_number, arrives_sample_handling, before_sample_handling, food_samples_number, food_samples_weights, plan, seasson_end, seasson_start, storage_conditions, sampling_origin_id) VALUES (1, 'analysis', 3, 3, 'wash, peel separated', 'Transport at -5C', 10, 3000.0, '10 fruits collected for each sample', TO_DATE('2016-03-13','YYYY-MM-DD'), TO_DATE('2016-01-13','YYYY-MM-DD'), 'Frozen -80C', 1);
INSERT INTO reference (id, biblio_id, doi, isbn, issn, issue_number, pages_number, published_date, publisher, publisher_location, title, url, volume_number, origin_id, reference_type_id) VALUES (1, '1', NULL, NULL, NULL, 4, '55-67', TO_DATE('2016-01-01','YYYY-MM-DD'), 'Food Composition', 'London', 'Nutritional composition of red guava fruits', NULL, 1, NULL, 1);
INSERT INTO reference_author (reference, authors) VALUES (1, 'Thomas Hazell');
INSERT INTO reference_author (reference, authors) VALUES (1, 'Daniela Beltrame');
INSERT INTO food_characteristic (id, max_value, min_value, "name", unit, "value", characteristic_type) VALUES (6, NULL, NULL, 'FOOD_WEIGHT', NULL, 50.0, '6');
INSERT INTO food_characteristic (id, max_value, min_value, "name", unit, "value", characteristic_type) VALUES (3, NULL, NULL, 'PH', NULL, 6.0, '3');
INSERT INTO food_characteristic (id, max_value, min_value, "name", unit, "value", characteristic_type) VALUES (1, NULL, NULL, 'DENSITY', NULL, NULL, '1');
INSERT INTO food_characteristic (id, max_value, min_value, "name", unit, "value", characteristic_type) VALUES (5, NULL, NULL, 'FOOD_SIZE', NULL, 24.0, '5');
INSERT INTO food_characteristic (id, max_value, min_value, "name", unit, "value", characteristic_type) VALUES (2, NULL, NULL, 'EDIBLE_PORTION', NULL, 67.0, '2');
INSERT INTO food_characteristic (id, max_value, min_value, "name", unit, "value", characteristic_type) VALUES (4, NULL, NULL, 'SOLID_SOLUBLE', NULL, NULL, '4');
INSERT INTO general_analysis (id, density_id, edible_portion_id, food_size_id, food_weight_id, ph_id, solid_soluble_id) VALUES (1, 1, 2, 5, 6, 3, 4);
INSERT INTO food (id, grade, manufacturer, "name", notes, recipe_procedure, scientific_name, shape_form, taxon_rank, agricultural_condition_id, colour_id, contact_surface_id, cooking_degree_id, general_analysis_id, physical_state_id, preservation_method_id, food_processing_id, ripeness_maturity_id, sampling_id, storage_condition_id, food_group_id, food_type_id, part_plant_animal_id, reference_id) VALUES (1, NULL, NULL, 'Red guava', NULL, NULL, 'Psidium cattleianum Sabine', NULL, 'Species', 1, 1, NULL, 1, 1,  1, NULL, 1, 1, 1, NULL, 6, 1, 6, 1);
INSERT INTO nutrient (id, max_value, min_value, "name", num_studies, unit, "value", nutrient_type, food_id) VALUES (4, 1.0, 1.0, 'ASP', NULL, NULL, 1.0, '6', 1);
INSERT INTO nutrient (id, max_value, min_value, "name", num_studies, unit, "value", nutrient_type, food_id) VALUES (2, 1.0, 1.0, 'WATER', NULL, NULL, 1.0, '2', 1);
INSERT INTO nutrient (id, max_value, min_value, "name", num_studies, unit, "value", nutrient_type, food_id) VALUES (3, 1.0, 1.0, 'ASH', NULL, NULL, 1.0, '3', 1);
INSERT INTO nutrient (id, max_value, min_value, "name", num_studies, unit, "value", nutrient_type, food_id) VALUES (1, 1.0, 1.0, 'ENERGY', NULL, NULL, 1.0, '1', 1);



